CREATE DATABASE FACTURACION
GO
USE FACTURACION
GO


CREATE TABLE CLIENTES(
ID INT IDENTITY(1,1),
NOMBRE VARCHAR(75),
APELLIDO VARCHAR(75),
FECHA_NACIMIENTO DATETIME
CONSTRAINT pk_clientes PRIMARY KEY (ID)
)

CREATE TABLE FORMAS_PAGO(
ID INT IDENTITY(1,1),
FORMA_PAGO VARCHAR(75)
CONSTRAINT pk_formas_pago PRIMARY KEY (ID)
)

CREATE TABLE ARTICULOS(
ID INT IDENTITY(1,1),
ARTICULO VARCHAR(75),
PRE_UNITARIO DECIMAL(12,2)
CONSTRAINT pk_articulos PRIMARY KEY (ID)
)

CREATE TABLE FACTURAS(
NRO_FACTURA INT IDENTITY(1,1),
FECHA DATETIME,
id_forma_pago INT,
id_cliente INT
CONSTRAINT pk_facturas PRIMARY KEY (NRO_FACTURA),
CONSTRAINT fk_facturas_formas_pago FOREIGN KEY (id_forma_pago)
REFERENCES formas_pago (id),
CONSTRAINT fk_facturas_clientes FOREIGN KEY (id_cliente)
REFERENCES clientes (id)
)

CREATE TABLE DETALLE_FACTURAS(
ID_DETALLE INT IDENTITY(1,1),
NRO_FACTURA INT,
PRECIO DECIMAL(12,2),
ID_ARTICULO INT,
CANTIDAD INT
CONSTRAINT pk_detalle_facturas PRIMARY KEY (id_detalle),
CONSTRAINT fk_detalle_facturas_facturas FOREIGN KEY (NRO_FACTURA)
REFERENCES facturas (NRO_FACTURA),
CONSTRAINT fk_detalle_facturas_articulos FOREIGN KEY (ID_ARTICULO)
REFERENCES ARTICULOS (ID)
)