CREATE DATABASE ALMACEN
GO 
USE ALMACEN
GO

CREATE TABLE PRODUCTOS(
CODIGO INT IDENTITY(1,1) NOT NULL,
N_PRODUCTO VARCHAR(50) NOT NULL,
PRECIO FLOAT NOT NULL,
STOCK INT NOT NULL,
ESTA_ACTIVO BIT NOT NULL
)


-- PROCEDIMIENTOS ALMACENADOS
GO


CREATE PROCEDURE SP_RECUPERAR_PRODUCTOS
AS
BEGIN
	SELECT * FROM PRODUCTOS
END
-------------------------------------------------------------
GO

CREATE PROCEDURE SP_GUARDAR_PRODUCTO
@CODIGO INT, @NOMBRE VARCHAR(50),
@PRECIO FLOAT,@STOCK INT
AS
BEGIN 
IF @CODIGO = 0
	BEGIN
		INSERT INTO PRODUCTOS(N_PRODUCTO,PRECIO,STOCK,ESTA_ACTIVO)
		VALUES(@NOMBRE,@PRECIO,@STOCK,1) --EL VALOR 1 EQUIVALE A TRUE
	END
ELSE
	BEGIN
		UPDATE PRODUCTOS
		SET N_PRODUCTO = @NOMBRE, PRECIO = @PRECIO, STOCK = @STOCK
		WHERE CODIGO = @CODIGO
	END
END

INSERT INTO PRODUCTOS (N_PRODUCTO, PRECIO, STOCK, ESTA_ACTIVO)
VALUES ('Iphone 13', 700, 25, 1);
INSERT INTO PRODUCTOS (N_PRODUCTO, PRECIO, STOCK, ESTA_ACTIVO)
VALUES ('Iphone 15', 100, 30, 1);
INSERT INTO PRODUCTOS (N_PRODUCTO, PRECIO, STOCK, ESTA_ACTIVO)
VALUES ('Galaxy A55', 700, 25, 1);
